# Generated by Django 2.2.4 on 2020-12-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister_app', '0002_auto_20201216_2319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
